# Generated by Django 2.2.6 on 2020-01-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('like', '左滑喜欢'), ('slike', '右滑超级喜欢'), ('unlike', '上滑不喜欢')], max_length=16, verbose_name='滑动类型')),
                ('source_id', models.IntegerField(verbose_name='滑动者的uid')),
                ('target_id', models.IntegerField(verbose_name='被滑动者的uid')),
                ('stime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
