# Generated by Django 2.2.6 on 2020-01-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0003_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='flag',
            field=models.CharField(choices=[('like', '左滑喜欢'), ('superlike', '右滑超级喜欢'), ('unlike', '上滑不喜欢')], max_length=16, verbose_name='滑动类型'),
        ),
    ]
