# Generated by Django 2.2.6 on 2020-01-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiper', '0004_auto_20200104_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swiper',
            old_name='flag',
            new_name='type',
        ),
    ]
