# Generated by Django 2.2.6 on 2020-01-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性'), ('no', '无性'), ('hidden', '隐藏'), ('unknown', '未知')], max_length=10, verbose_name='性别'),
        ),
    ]
